# Generated by Django 5.2.7 on 2025-10-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Karyawan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "nomor_telepon",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("posisi", models.CharField(max_length=100)),
                ("tanggal_bergabung", models.DateTimeField(auto_now=True)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("P", "Pria"), ("W", "Wanita")], max_length=1
                    ),
                ),
            ],
        ),
    ]
